### ISSUE TITLE
Suggestion: Replace RGB Node for RGB CLI on the RGB website

### ISSUE THREAD

**Issue by 22388o** [RGB-WG/rgb.tech#21]
As RGB Node was [archived](https://github.com/RGB-WG/rgb-node), could add RGB CLI github there. Like this stay less confuse and more clear for devs.

This [section](https://rgb.tech/install/#node)

**Comment by dr-orlovsky** [comment]
The RGB command-line tool is listed on the website and described right in the section above RGB Node.

The RGB Node is temporarily archieved - it will be developed in the future, but since it is not a priority and people constantly try to file issues there, I archived it for now.

The current site section on RGB Node provide the correct information: "Please pay attention that the current version of RGB Node supports the previous RGB protocol version, v0.9, and is not compatible with the latest protocol changes. Until a new RGB Node v0.10 is released it is recommended to use the RGB command-line tool as described in the previous section." 

It also describes what is the purpose of the node: "RGB Node is a daemon/service which runs in the background, provides RPC API, and allows you to always be online and accept incoming RGB transfers without any third-party server."

Also please note that `rgb` command-line tool and `rgb-cli` are two different things.

I.e. I do not see why and how to change what is written on the website.

**Comment by 22388o** [comment]
>Also please note that rgb command-line tool and rgb-cli are two different things.
 
Ok 

>I.e. I do not see why and how to change what is written on the website.

It is only suggestion, thinking now make you said make sense

>The RGB Node is temporarily archieved - it will be developed in the future, but since it is not a priority and people constantly try to file issues there, I archived it for now.

Now is clear

Anyway, thanks for update and info. I'll close this Issue 👍
